name: C++ CI (macOS)

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew install cmake ninja llvm abseil
        echo "/opt/homebrew/opt/llvm/bin" >> $GITHUB_PATH

    - name: Create build directory
      run: mkdir build

    - name: Configure with CMake
      run: |
        export CC=/opt/homebrew/opt/llvm/bin/clang
        export CXX=/opt/homebrew/opt/llvm/bin/clang++
        cmake -S . -B build -G Ninja -DCMAKE_C_COMPILER=/opt/homebrew/opt/llvm/bin/clang -DCMAKE_CXX_COMPILER=/opt/homebrew/opt/llvm/bin/clang++

    - name: Build with CMake
      run: cmake --build build
